name: build_and_push

on: 
  push:
    branches:
      - main
      
jobs: 
  build:
    name: buildJob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: appBuild
        working-directory: todo-app
        run: docker build -t achinta1/todo:latest .

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: achinta1
          password: ${{ secrets.DOCKER_PAT }}

      - name: image push to dockerhub
        run: docker push achinta1/todo:latest


          
