name: build_and_push

on: 
  push:
    branches:
      - main
env:
  # Update image version here, this should be same as in deployment.yaml
  IMAGE_VERSION: '1.0'
  
permissions:
  id-token: write
  contents: read
  
jobs: 
  build:
    name: buildJob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: appBuild
        working-directory: todo-app
        run: docker build -t achinta1/todo:v$IMAGE_VERSION .

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: achinta1
          password: ${{ secrets.DOCKER_PAT }}

      - name: image push to dockerhub
        run: docker push achinta1/todo:v$IMAGE_VERSION

  deploy:
    name: deploy App to cluster
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: aks login
        run: az aks get-credentials --resource-group ${{ secrets.RG_NAME }} --name ${{ secrets.AKS_NAME }} --overwrite-existing

      - name: deploy to aks
        working-directory: manifests
        run: | 
          kubectl apply -f deployment.yaml -n todo --validate=false
          kubectl apply -f service.yaml -n todo --validate=false
          kubectl apply -f ingress.yaml -n todo --validate=false

          

      
                
          
